### ISSUE TITLE
options parameter in Repository.writeFile is required instead of optional

### ISSUE THREAD

**Issue by limin** [github-tools/github#520] opened 2018-09-05 01:48 UTC
The below error is thrown when Repository.writeFile is called without passing options parameter

TypeError: options is undefined 

See api doc at: http://github-tools.github.io/github/docs/3.1.0/Repository.html#writeFile

**Comment by WJXHenry** [comment] 2019-05-02 21:35
Hey @limin, I was unable to reproduce this error except for when I passed in 'undefined' as a parameter to options. Would you be able to provide more details on how you got this error?

**Comment by WJXHenry** [comment] 2019-05-02 22:04
Hey @j-rewerts, I think @limin might have been passing in 'undefined' as a parameter for options. Feel free to close this issue.

**Comment by j-rewerts** [comment] 2019-05-02 22:17
Closing. @limin Feel free to reach out and let us know if this is still an issue. We can always reopen this issue.

**Closed by j-rewerts** 2019-05-02 22:17 UTC
